[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024_petiton_biobd-bsnip-predict-dx"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8.*"
scikit-learn = ">=1.3.2,<2"
pandas = ">=2.0.3,<3"
ipykernel = ">=6.29.5,<7"
pip = ">=24.3.1,<25"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
semopy = { version = "*"}

